

-
  version: "{build}"

  image: Visual Studio 2019 Preview

  branches:
    only:
      - master

  configuration: Release
  
-
  version: "{build}"

  image: Visual Studio 2019 Preview
  configuration: Debug

  cache: 
    - c:\tools\vcpkg\installed\
        
  install:
    - cd %APPVEYOR_BUILD_FOLDER%
    - git submodule update --init --recursive
    - cd c:\tools\vcpkg
    - git pull
    - vcpkg update
    - vcpkg integrate install
    - vcpkg install nlohmann-json:x86-windows-static nlohmann-json:x64-windows-static
    #- vcpkg install boost-program-options:x64-windows-static boost-property-tree:x64-windows-static
    - cd %APPVEYOR_BUILD_FOLDER%
        
  before_build:
    - mkdir build
    - mkdir vcproj
    - mkdir vcproj64
    - cd vcproj
    - cmake .. -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DVCPKG_TARGET_TRIPLET=x86-windows-static
    - cd ..
    - cd vcproj64
    - cmake .. -G "Visual Studio 15 2017 Win64" -DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DUSE_64BIT_BUILD=ON -DVCPKG_TARGET_TRIPLET=x64-windows-static
    - cd ..

  build:
    parallel: true
    verbosity: minimal

  build_script:
    - msbuild vcproj\grad_mtg.sln /m 
    - msbuild vcproj64\grad_mtg.sln /m 
    - tools\hemtt.exe build
    
  on_success:
    - ps: .\tools\package_artifacts.ps1

  artifacts:
  - path: build\win64\Debug\grad_mtg_x64.dll
    name: win64_dll
  - path: build\win64\Debug\grad_mtg_x64.pdb
    name: win64_pdb
  - path: addons\grad_mtg.pbo
    name: grad_mtg_pbo
