version: "{build}"

image: Visual Studio 2019 Preview

branches:
  only:
  - master
  - appveyor

configuration:
- Debug
#cache: 
  #- c:\tools\vcpkg\installed\
clone_script:
  - cmd: >-
      git clone -q --branch=%APPVEYOR_REPO_BRANCH% https://github.com/%APPVEYOR_REPO_NAME%.git %APPVEYOR_BUILD_FOLDER%
      && cd %APPVEYOR_BUILD_FOLDER%
      && git checkout -qf %APPVEYOR_REPO_COMMIT%
      && git submodule update --init --recursive
      
install:
  - cmd: vcpkg integrate install
  - vcpkg install nlohmann-json:x86-windows
  - vcpkg install nlohmann-json:x86-windows-static
  - vcpkg install nlohmann-json:x64-windows
  - vcpkg install nlohmann-json:x64-windows-static
      
before_build:
  - mkdir build
  - mkdir vcproj
  - mkdir vcproj64
  - cd vcproj
  - cmake .. -G "Visual Studio 15 2017" -DCMAKE_TOOLCHAIN_FILE=C:/Tools/vcpkg/scripts/buildsystems/vcpkg.cmake -DBOOST_ROOT=C:\Libraries\boost_1_69_0
  - cd ..
  - cd vcproj64
  - cmake .. -G "Visual Studio 15 2017 Win64" "-DUSE_64BIT_BUILD=ON" "-DCMAKE_TOOLCHAIN_FILE=c:/tools/vcpkg/scripts/buildsystems/vcpkg.cmake" "-DBOOST_ROOT=C:\Libraries\boost_1_69_0"
  - cd ..

build:
  parallel: true
  verbosity: minimal

build_script:
  - msbuild vcproj\grad_mtg.sln /m
  - msbuild vcproj64\grad_mtg.sln /m 
  
on_success:
  # TODO
  #- ps: .\tools\ci_publish_artifacts.ps1

artifacts:
- path: build\win32\Debug\grad_mtg.dll
  name: win32_dll
- path: build\win32\Debug\grad_mtg.pdb
  name: win32_pdb
- path: build\win64\Debug\grad_mtg_x64.dll
  name: win64_dll
- path: build\win64\Debug\grad_mtg_x64.pdb
  name: win64_pdb
